In [2]:
import numpy as np
arr1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("Array Elements:\n",arr1)

Array Elements:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print("Dimensions of array:",arr1.ndim)

Dimensions of array: 2


In [5]:
arr2=np.zeros(3)
arr3=np.zeros((4,4))
print("1D arrays with zeros:\n",arr2)
print("2D arrays with zeros:\n",arr3)

1D arrays with zeros:
 [0. 0. 0.]
2D arrays with zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr4=np.identity(5)
print("2D identity array:\n",arr4)

2D identity array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
print("Element in second row,first column:",arr1[1,0])

Element in second row,first column: 4


In [9]:
print("All values in second row:",arr1[1,:])

All values in second row: [4 5 6]


In [10]:
print("All values from second column:\n", arr1[:, 1])

All values from second column:
 [2 5 8]


In [11]:
print("Last column values:\n", arr1[:, -1])

Last column values:
 [3 6 9]


In [12]:
print("Values from second and third row:\n", arr1[1:3, :])

Values from second and third row:
 [[4 5 6]
 [7 8 9]]


In [13]:
arr5=np.arange(1,5,1)
print("Array in the given range:\n",arr5)

Array in the given range:
 [1 2 3 4]


In [14]:
transpose=arr1.T
print("Transposed Matrix:\n",transpose)

Transposed Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
arr6=[[1,2],[3,8]]
print("Determinant of the matrix:\n",np.linalg.det(arr6))

Determinant of the matrix:
 1.9999999999999998


In [17]:
print("Diagonal elements:\n", np.diag(arr1))

Diagonal elements:
 [1 5 9]


In [18]:
x1 = np.array([[1, 2], [3, 4]])
x2 = np.array([[8, 7], [6,9]])
print("Addition:\n",x1+x2)
print("Subtraction:\n",x1-x2)
print("Multiplication:\n",np.dot(x1,x2))

Addition:
 [[ 9  9]
 [ 9 13]]
Subtraction:
 [[-7 -5]
 [-3 -5]]
Multiplication:
 [[20 25]
 [48 57]]


In [19]:
arr7=np.random.randint(1,20,(3,5))
print("Random numbered Array:\n",arr7)

Random numbered Array:
 [[17 18  2 11  5]
 [19 17  4 12 17]
 [ 5 18  4 19  1]]


In [22]:
arr8=np.linspace(1,10,5)
print("Equal step size:\n",arr8)

Equal step size:
 [ 1.    3.25  5.5   7.75 10.  ]
